
services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: main_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-net

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --requirepass mypassword
    networks:
      - app-net
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "mypassword", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    environment:
      REDIS_HOSTS: local:redis:6379
      REDIS_PASSWORD: mypassword
    ports:
      - "8087:8081"
    depends_on:
      - redis
    networks:
      - app-net


  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - ./pgadmin-config/servers.json:/pgadmin4/servers.json
    networks:
      - app-net

  # nginx:
  #   image: nginx:1.26-alpine
  #   container_name: antoree-nginx
  #   depends_on:
  #     - backend
  #   ports:
  #     - "${NGINX_HTTP_PORT}:80"
  #     - "${NGINX_HTTPS_PORT}:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  #     - ./public:/usr/share/nginx/html:ro
  #   networks:
  #     - app-net

volumes:
  postgres-data:
    driver: local
  pgadmin-data:
    driver: local
  redis-data:
    driver: local
  redis-commander-data:
    driver: local

networks:
  app-net:
    driver: bridge
    name: app-network
